let library = [
    {
        id: "some-unique-id-1", // Generated by crypto.randomUUID()
        title: "The Great Adventure",
        author: "John Doe",
        pages: 350,
        read: true
    },
    {
        id: "some-unique-id-2",
        title: "The Mystery of the Sea",
        author: "Jane Smith",
        pages: 200,
        read: false
    },
    {
        id: "some-unique-id-3",
        title: "A Journey Through Time",
        author: "Emily White",
        pages: 420,
        read: true
    },
    {
        id: "some-unique-id-4",
        title: "The Hidden World",
        author: "David Brown",
        pages: 150,
        read: false
    },
    {
        id: "some-unique-id-5",
        title: "Exploring the Cosmos",
        author: "Sara Green",
        pages: 500,
        read: true
    },
    {
        id: "some-unique-id-6",
        title: "The Art of Cooking",
        author: "Tom Clark",
        pages: 120,
        read: false
    },
    {
        id: "some-unique-id-7",
        title: "The Silent Forest",
        author: "Alice Blue",
        pages: 230,
        read: true
    },
    {
        id: "some-unique-id-8",
        title: "Learning JavaScript",
        author: "Chris Black",
        pages: 300,
        read: true
    }
];



function Book(id,title, author, pages, read){
    this.id = id;
    this.title = title;
    this.author = author;
    this.pages = pages;
    this.read = read;
}

let formWin = document.querySelector(".form-win");
let createButton = document.getElementById("button-create");
let form = formWin.querySelector("form");

createButton.addEventListener('click', () =>{
    formWin.showModal();
} );

form.addEventListener('submit', function(event) {
    event.preventDefault(); 

    let title = form.querySelector('input[name="title"]').value;
    let author = form.querySelector('input[name="author"]').value;
    let pages = form.querySelector('input[name="pages"]').value;
    let read = form.querySelector('input[name="read"]').checked; 


    let book = new Book(
        crypto.randomUUID(),
        title,
        author,
        pages,
        read
    );

    library.push(book);

    let container = document.querySelector(".books");
    container.appendChild(createBookDiv(book.id, book.title, book.author, book.pages, book.read));

    formWin.close();
    form.reset();
});

function createBookDiv(id, title, author, pages, read){

    let parentDiv = document.createElement("div");
    parentDiv.className = "book";


    let titleSection = document.createElement("div");
    titleSection.className = "title-section";

    let bookTitle = document.createElement("h3");
    bookTitle.textContent = title;

    let checkbox = document.createElement("input");
    checkbox.type = "checkbox";
    checkbox.checked = read

    titleSection.appendChild(bookTitle);
    titleSection.appendChild(checkbox);


    let bookInfo = document.createElement("div");
    bookInfo.className = "book-info";

    let authorElem = document.createElement("p");
    authorElem.textContent = author;

    let pagesElem = document.createElement("p");
    pagesElem.textContent = pages;

    bookInfo.appendChild(authorElem);
    bookInfo.appendChild(pagesElem);

    let deleteBook = document.createElement("button");
    deleteBook.id = id;
    deleteBook.className = "delete-book"
    deleteBook.textContent = "Delete"; 

    deleteBook.addEventListener('click', function(event){
        let bookId = this.id;

        library = library.filter(book => book.id !== bookId);

        updateBooksDisplay();
    });
    
    parentDiv.appendChild(titleSection);
    parentDiv.appendChild(bookInfo);
    parentDiv.appendChild(deleteBook);


    return parentDiv;

}

function updateBooksDisplay() {
    let container = document.querySelector(".books"); 
    container.innerHTML = '';
    library.forEach(book => {
        container.appendChild(createBookDiv(book.id, book.title, book.author, book.pages, book.read));
    });
}
updateBooksDisplay();


